-- ============================================
-- DEPRECATED — consolidated into:
--   supabase/migrations/20260706190700_job_prep_schema.sql
-- ============================================
-- That single migration replaces all Job Prep SQL files:
--   migration_add_job_prep_analysis_fields.sql
--   migration_add_job_prep_tailored_resume.sql
--   migration_add_job_prep_interview_questions.sql
--   migration_add_job_prep_answer_sessions.sql
--   migration_add_job_prep_answer_rating.sql
--
-- Run via Supabase CLI (recommended):
--   supabase db push
-- or apply the migrations file directly with psql.
-- ============================================
